# Generated by Django 2.0.2 on 2019-08-29 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=260)),
                ('programming_language', models.CharField(max_length=260)),
                ('framework', models.CharField(max_length=260)),
                ('picture', models.ImageField(height_field='height', upload_to='images/', width_field='width')),
                ('height', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=0)),
                ('description', models.TextField(max_length=200)),
                ('link', models.CharField(max_length=500)),
                ('pub_date', models.DateTimeField()),
            ],
        ),
    ]
