# Generated by Django 2.0.2 on 2019-08-30 14:14

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myprojects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=600, null=True),
        ),
    ]
