# Generated by Django 2.0.2 on 2019-09-01 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojects', '0002_auto_20190830_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='file',
            field=models.FileField(default=1, upload_to='uploads/%Y/%m/%d/%H/%M/%S/'),
            preserve_default=False,
        ),
    ]
