# Generated by Django 2.0.2 on 2019-09-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojects', '0003_projects_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='slug',
            field=models.SlugField(default=1, max_length=250, unique_for_date='pub_date'),
            preserve_default=False,
        ),
    ]
