# Generated by Django 3.0.2 on 2020-01-20 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myprojects', '0004_projects_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='slug',
        ),
    ]
